config/urls.py
from django.contrib import admin
from django.urls import path, include
from word import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sword/', include('word.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

word/urls.py
from django.urls import path
from . import views

app_name = 'sword'

urlpatterns = [
    path('', views.index, name='index'),
    path('voca_book/<int:voca_id>', views.detail, name='detail'),
    path('voca_book/create/', views.voca_book_create, name='voca_book_create'),
    path('voca_book/modify/<int:voca_id>/', views.voca_book_modify, name='voca_book_modify'),
    path('voca_book/word/modify/<int:voca_id>/', views.words_modify, name='words_modify'),
    path('voca_book/delete/<int:voca_id>/', views.voca_book_delete, name='voca_book_delete'),
    path('voca_book/vote/<int:voca_id>/', views.voca_book_vote, name='voca_book_vote'),
    path('voca_book/vote/cancel/<int:voca_id>/', views.voca_vote_cancel, name='voca_vote_cancel'),
    path('voca_book/word/vote/<int:word_id>/', views.word_vote, name='word_vote'),
    path('voca_book/word/vote/cancel/<int:word_id>/', views.word_vote_cancel, name='word_vote_cancel'),
]

word/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models

class Voca_Book(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='voca_book_list')
    title = models.CharField(max_length=50)
    view = models.IntegerField(default=0)
    voter = models.ManyToManyField(User, related_name='voca_book_voter')
    from_lang = models.CharField(max_length=50, default='en-US')
    to_lang = models.CharField(max_length=50, default='ko-KR')
    create_date = models.DateTimeField(null=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    is_share = models.BooleanField(default=True)

class Word(models.Model):
    voca_book = models.ForeignKey(Voca_Book, on_delete=models.CASCADE)
    voter = models.ManyToManyField(User, related_name='word_voter')
    content = models.TextField(null=True)
    mean = models.TextField(null=True)

word/forms.py
from django import forms
from word.models import Voca_Book, Word

class VocaBookForm(forms.ModelForm):
    class Meta:
        model = Voca_Book
        fields = ['title', 'is_share', 'from_lang', 'to_lang']
        labels = {
            'title': '이름',
            'is_share': '공개 여부',
            'from_lang': '시작 언어',
            'to_lang': '도착 언어',
        }

class WordForm(forms.ModelForm):
    class Meta:
        model = Word  # 사용할 모델
        fields = ['content', 'mean']
        labels = {
            'content': '단어',
            'mean': '의미',
        }

word/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.utils import timezone, dateformat
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import Voca_Book, Word
from .forms import VocaBookForm, WordForm

def index(request):
    page = request.GET.get('page', '1')
    type = request.GET.get('type', 'all')
    kw = request.GET.get('kw', '')
    
    voca_book_list = Voca_Book.objects.filter(
        Q(is_share=True)
    ).order_by('-create_date')
    if request.user.is_authenticated:
        voca_book_mine = Voca_Book.objects.filter(
            Q(author__username__icontains=request.user.username)
        ).order_by('-create_date')
        voca_book_like = Voca_Book.objects.filter(
            Q(is_share=True) &
            Q(voter__username__icontains=request.user.username)
        ).order_by('-create_date')
    else:
        voca_book_mine = []
        voca_book_like = []
    
    if kw:
        if type == 'all':
            voca_book_list = voca_book_list.filter(
                Q(title__icontains=kw) |
                Q(author__username__icontains=kw)  # 질문 글쓴이 검색
            ).distinct()
        elif type == 'mine':
            voca_book_mine = voca_book_mine.filter(
                Q(title__icontains=kw) |
                Q(author__username__icontains=kw)  # 질문 글쓴이 검색
            ).distinct()
        elif type == 'like':
            voca_book_like = voca_book_like.filter(
                Q(title__icontains=kw) |
                Q(author__username__icontains=kw)
            ).distinct()
    
    paginator_all = Paginator(voca_book_list, 10)
    paginator_mine = Paginator(voca_book_mine, 10)
    paginator_like = Paginator(voca_book_like, 10)
    
    page_obj_all = paginator_all.get_page(page if type == 'all' else 1)
    page_obj_mine = paginator_mine.get_page(page if type == 'mine' else 1)
    page_obj_like = paginator_like.get_page(page if type == 'like' else 1)
    context = {'voca_book_list': page_obj_all, 'voca_book_mine': page_obj_mine, \
            'voca_book_like': page_obj_like, 'type': type, 'page': page, 'kw': kw}
    return render(request, 'word/voca_book_list.html', context)

def detail(request, voca_id):
    voca_book = get_object_or_404(Voca_Book, pk=voca_id)
    word_list = voca_book.word_set.all()
    word_mark = Word.objects.filter(
            Q(voca_book__id=voca_id) &
            Q(voter__username__icontains=request.user.username)
        )
    context = {'voca_book': voca_book, 'word_list': word_list, 'word_mark': word_mark}
    voca_book.view += 1
    voca_book.save()
    return render(request, 'word/word_list.html', context)

@login_required(login_url='common:login')
def voca_book_create(request):
    if request.method == 'POST':
        title = request.POST['title']
        if request.POST['is_share'] == 'open': is_share = True
        elif request.POST['is_share'] == 'close': is_share = False
        from_lang = request.POST['from_lang']
        to_lang = request.POST['to_lang']
        
        form = VocaBookForm({'title': title, 'is_share': is_share, \
                            'from_lang': from_lang, 'to_lang': to_lang})
        if form.is_valid():
            voca_book = form.save(commit=False)
            voca_book.author = request.user
            voca_book.create_date = timezone.now()
            voca_book.save()
            return redirect('sword:index')
    else:
        form = VocaBookForm()
    context = {'form': form}
    return render(request, 'word/voca_book_form.html', context)

@login_required(login_url='common:login')
def voca_book_modify(request, voca_id):
    voca_book = get_object_or_404(Voca_Book, pk=voca_id)
    if request.user != voca_book.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('sword:detail', voca_id=voca_book.id)
    if request.method == "POST":
        title = request.POST['title']
        if request.POST['is_share'] == 'open': is_share = True
        elif request.POST['is_share'] == 'close': is_share = False
        from_lang = request.POST['from_lang']
        to_lang = request.POST['to_lang']
        
        form = VocaBookForm({'title': title, 'is_share': is_share, \
                            'from_lang': from_lang, 'to_lang': to_lang}, instance=voca_book)
        if form.is_valid():
            voca_book = form.save(commit=False)
            voca_book.modify_date = timezone.now()
            voca_book.save()
            return redirect('sword:detail', voca_id=voca_book.id)
    else:
        form = VocaBookForm(instance=voca_book)
    context = {'form': form}
    return render(request, 'word/voca_book_form.html', context)

@login_required(login_url='common:login')
def words_modify(request, voca_id):
    voca_book = get_object_or_404(Voca_Book, pk=voca_id)
    if request.user != voca_book.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('sword:detail', voca_id=voca_book.id)
    if request.method == "POST":
        new_words = []
        leng = len(request.POST.getlist('content'))
        words = voca_book.word_set.all()
        for i in range(leng):
            content = request.POST.getlist('content')[i]
            mean = request.POST.getlist('mean')[i]
            new_word = {'content': content, 'mean': mean}
            form = WordForm({'content': content, 'mean': mean})
            if form.is_valid():
                new_words.append(new_word)
        idx = 0
        for word in words:
            if idx < len(new_words):
                form = WordForm(new_words[idx], instance=word)
                form.save()
                idx += 1
            else:
                temp = word
                temp.delete()
        if len(new_words) > len(words):
            for i in range(idx, len(new_words)):
                form = WordForm(new_words[i])
                word = form.save(commit=False)
                word.voca_book = voca_book
                word.save()
        voca_book.modify_date = timezone.now()
        voca_book.save()
        return redirect('sword:detail', voca_id=voca_book.id)
    else:
        word_forms = []
        for word in voca_book.word_set.all():
            form = WordForm(instance=word)
            word_forms.append(form)
    context = {'voca_book': voca_book, 'forms': word_forms}
    return render(request, 'word/word_form.html', context)

@login_required(login_url='common:login')
def voca_book_delete(request, voca_id):
    voca_book = get_object_or_404(Voca_Book, pk=voca_id)
    if request.user != voca_book.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('sword:detail', voca_id=voca_book.id)
    voca_book.delete()
    return redirect('sword:index')

@login_required(login_url='common:login')
def voca_book_vote(request, voca_id):
    voca_book = get_object_or_404(Voca_Book, pk=voca_id)
    voca_book.voter.add(request.user)
    return redirect('sword:index')

@login_required(login_url='common:login')
def voca_vote_cancel(request, voca_id):
    voca_book = get_object_or_404(Voca_Book, pk=voca_id)
    voca_book.voter.remove(request.user)
    return redirect('sword:index')   

@login_required(login_url='common:login')
def word_vote(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    word.voter.add(request.user)
    word.voca_book.view -= 1
    word.voca_book.save()
    return redirect('sword:detail', voca_id=word.voca_book.id)

@login_required(login_url='common:login')
def word_vote_cancel(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    word.voter.remove(request.user)
    word.voca_book.view -= 1
    word.voca_book.save()
    return redirect('sword:detail', voca_id=word.voca_book.id)

word/templates/word/voca_book_form.html
{% extends 'base.html' %}
{% block content %}
<div class="center-form">
    <div class="type">
        단어장 설정
    </div>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
        <div class="form-error">
            {% for field in form %}
                {% if field.errors %}
                <div class="error">
                    <span>{{ field.label }}</span>
                    {{ field.errors }}
                </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="form-input">
            <div class="set">
                <div class="title">
                    단어장 제목
                    <strong>*</strong>
                </div>
                <div class="value">
                    <input type="text" name="title" id="title" placeholder="50자 이내로 입력해주세요."
                        value="{{ form.title.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="set">
                <div class="title">시작 언어</div>
                <div class="value">
                    <select name="from_lang" id="from_lang">
                        <option value="el-GR" {% if form.from_lang.value == 'el-GR' %}selected{% endif %}>그리스어</option>
                        <option value="nl-NL" {% if form.from_lang.value == 'nl-NL' %}selected{% endif %}>네덜란드어</option>
                        <option value="no-NO" {% if form.from_lang.value == 'no-NO' %}selected{% endif %}>노르웨이어</option>
                        <option value="da-DK" {% if form.from_lang.value == 'da-DK' %}selected{% endif %}>덴마크어</option>
                        <option value="de-DE" {% if form.from_lang.value == 'de-DE' %}selected{% endif %}>독일어</option>
                        <option value="ru-RU" {% if form.from_lang.value == 'ru-RU' %}selected{% endif %}>러시아어</option>
                        <option value="ro-RO" {% if form.from_lang.value == 'ro-RO' %}selected{% endif %}>루마니아어</option>
                        <option value="bn-BD" {% if form.from_lang.value == 'bn-BD' %}selected{% endif %}>벵골어</option>
                        <option value="sv-SE" {% if form.from_lang.value == 'sv-SE' %}selected{% endif %}>스웨덴어</option>
                        <option value="es-ES" {% if form.from_lang.value == 'es-ES' %}selected{% endif %}>스페인어</option>
                        <option value="sk-SK" {% if form.from_lang.value == 'sk-SK' %}selected{% endif %}>슬로바키아어</option>
                        <option value="ar-SA" {% if form.from_lang.value == 'ar-SA' %}selected{% endif %}>아랍어</option>
                        <option value="en-US" {% if form.from_lang.value == 'en-US' %}selected{% endif %}>영어</option>
                        <option value="it-IT" {% if form.from_lang.value == 'it-IT' %}selected{% endif %}>이탈리아어</option>
                        <option value="id-ID" {% if form.from_lang.value == 'id-ID' %}selected{% endif %}>인도네시아어</option>
                        <option value="ja-JP" {% if form.from_lang.value == 'ja-JP'%}selected{% endif %}>일본어</option>
                        <option value="zh-CN" {% if form.from_lang.value == 'zh-CN' %}selected{% endif %}>중국어</option>
                        <option value="cs-CZ" {% if form.from_lang.value == 'cs-CZ' %}selected{% endif %}>체코어</option>
                        <option value="th-TH" {% if form.from_lang.value == 'th-TH' %}selected{% endif %}>태국어</option>
                        <option value="tr-TR" {% if form.from_lang.value == 'tr-TR' %}selected{% endif %}>튀르키예어</option>
                        <option value="pt-PT" {% if form.from_lang.value == 'pt-PT' %}selected{% endif %}>포르투갈어</option>
                        <option value="pl-PL" {% if form.from_lang.value == 'pl-PL' %}selected{% endif %}>폴란드어</option>
                        <option value="fr-FR" {% if form.from_lang.value == 'fr-FR' %}selected{% endif %}>프랑스어</option>
                        <option value="fi-FI" {% if form.from_lang.value == 'fi-FI' %}selected{% endif %}>핀란드어</option>
                        <option value="ko-KR" {% if form.from_lang.value == 'ko-KR'%}selected{% endif %}>한국어</option>
                        <option value="hu-HU" {% if form.from_lang.value == 'hu-HU'%}selected{% endif %}>헝가리어</option>
                        <option value="he-IL" {% if form.from_lang.value == 'he-IL' %}selected{% endif %}>히브리어</option>
                        <option value="hi-IN" {% if form.from_lang.value == 'hi-IN' %}selected{% endif %}>힌디어</option>
                    </select>
                </div>
            </div>
            <div class="set">
                <div class="title">도착 언어</div>
                <div class="value">
                    <select name="to_lang" id="to_lang">
                        <option value="el-GR" {% if form.to_lang.value == 'el-GR' %}selected{% endif %}>그리스어</option>
                        <option value="nl-NL" {% if form.to_lang.value == 'nl-NL' %}selected{% endif %}>네덜란드어</option>
                        <option value="no-NO" {% if form.to_lang.value == 'no-NO' %}selected{% endif %}>노르웨이어</option>
                        <option value="da-DK" {% if form.to_lang.value == 'da-DK' %}selected{% endif %}>덴마크어</option>
                        <option value="de-DE" {% if form.to_lang.value == 'de-DE' %}selected{% endif %}>독일어</option>
                        <option value="ru-RU" {% if form.to_lang.value == 'ru-RU' %}selected{% endif %}>러시아어</option>
                        <option value="ro-RO" {% if form.to_lang.value == 'ro-RO' %}selected{% endif %}>루마니아어</option>
                        <option value="bn-BD" {% if form.to_lang.value == 'bn-BD' %}selected{% endif %}>벵골어</option>
                        <option value="sv-SE" {% if form.to_lang.value == 'sv-SE' %}selected{% endif %}>스웨덴어</option>
                        <option value="es-ES" {% if form.to_lang.value == 'es-ES' %}selected{% endif %}>스페인어</option>
                        <option value="sk-SK" {% if form.to_lang.value == 'sk-SK' %}selected{% endif %}>슬로바키아어</option>
                        <option value="ar-SA" {% if form.to_lang.value == 'ar-SA' %}selected{% endif %}>아랍어</option>
                        <option value="en-US" {% if form.to_lang.value == 'en-US' %}selected{% endif %}>영어</option>
                        <option value="it-IT" {% if form.to_lang.value == 'it-IT' %}selected{% endif %}>이탈리아어</option>
                        <option value="id-ID" {% if form.to_lang.value == 'id-ID' %}selected{% endif %}>인도네시아어</option>
                        <option value="ja-JP" {% if form.to_lang.value == 'ja-JP'%}selected{% endif %}>일본어</option>
                        <option value="zh-CN" {% if form.to_lang.value == 'zh-CN' %}selected{% endif %}>중국어</option>
                        <option value="cs-CZ" {% if form.to_lang.value == 'cs-CZ' %}selected{% endif %}>체코어</option>
                        <option value="th-TH" {% if form.to_lang.value == 'th-TH' %}selected{% endif %}>태국어</option>
                        <option value="tr-TR" {% if form.to_lang.value == 'tr-TR' %}selected{% endif %}>튀르키예어</option>
                        <option value="pt-PT" {% if form.to_lang.value == 'pt-PT' %}selected{% endif %}>포르투갈어</option>
                        <option value="pl-PL" {% if form.to_lang.value == 'pl-PL' %}selected{% endif %}>폴란드어</option>
                        <option value="fr-FR" {% if form.to_lang.value == 'fr-FR' %}selected{% endif %}>프랑스어</option>
                        <option value="fi-FI" {% if form.to_lang.value == 'fi-FI' %}selected{% endif %}>핀란드어</option>
                        <option value="ko-KR" {% if form.to_lang.value == 'ko-KR'%}selected{% endif %}>한국어</option>
                        <option value="hu-HU" {% if form.to_lang.value == 'hu-HU'%}selected{% endif %}>헝가리어</option>
                        <option value="he-IL" {% if form.to_lang.value == 'he-IL' %}selected{% endif %}>히브리어</option>
                        <option value="hi-IN" {% if form.to_lang.value == 'hi-IN' %}selected{% endif %}>힌디어</option>
                    </select>
                </div>
            </div>
            <div class="set">
                <div class="title">공개 여부</div class="title">
                <div class="value">
                    <select name="is_share" id="is_share">
                        <option value="open" {% if form.is_share.value %}selected{% endif %}>공개</option>
                        <option value="close" {% if not form.is_share.value %}selected{% endif %}>비공개</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="submit">
            <button type="submit">저장하기</button>
        </div>
    </form>
</div>
{% endblock %}

word/templates/word/word_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="center">
    <div class="book-list">
        {% if user.is_authenticated %}
            {% if voca_book in user.voca_book_voter.all %}
            <a href="{% url 'sword:voca_vote_cancel' voca_book.id %}">
                <img src="{% static "image/star.png" %}">
            </a>
            {% else %}
            <a href="{% url 'sword:voca_book_vote' voca_book.id %}">
                <img src="{% static "image/empty.png" %}">
            </a>
            {% endif %}
        {% endif %}
        <div class="title">
            <div class="lang">
                {% if voca_book.from_lang == 'ko-KR' %} <img src="{% static "image/korea.png" %}">
                {% elif voca_book.from_lang == 'ja-JP' %} <img src="{% static "image/japan.png" %}">
                {% elif voca_book.from_lang == 'zh-CN' %} <img src="{% static "image/china.png" %}">
                {% elif voca_book.from_lang == 'en-US' %} <img src="{% static "image/usa.png" %}">
                {% elif voca_book.from_lang == 'es-ES' %} <img src="{% static "image/spain.png" %}">
                {% elif voca_book.from_lang == 'it-IT' %} <img src="{% static "image/italy.png" %}">
                {% elif voca_book.from_lang == 'fr-FR' %} <img src="{% static "image/france.png" %}">
                {% elif voca_book.from_lang == 'de-DE' %} <img src="{% static "image/germany.png" %}">
                {% elif voca_book.from_lang == 'ru-RU' %} <img src="{% static "image/russia.png" %}">
                {% elif voca_book.from_lang == 'ar-SA' %} <img src="{% static "image/saudi-arabia.png" %}">
                {% elif voca_book.from_lang == 'he-IL' %} <img src="{% static "image/israel.png" %}">
                {% elif voca_book.from_lang == 'hi-IN' %} <img src="{% static "image/india.png" %}">
                {% elif voca_book.from_lang == 'id-ID' %} <img src="{% static "image/indonesia.png" %}">
                {% elif voca_book.from_lang == 'th-TH' %} <img src="{% static "image/thailand.png" %}">
                {% elif voca_book.from_lang == 'bn-BD' %} <img src="{% static "image/bangladesh.png" %}">
                {% elif voca_book.from_lang == 'tr-TR' %} <img src="{% static "image/turkey.png" %}">
                {% elif voca_book.from_lang == 'hu-HU' %} <img src="{% static "image/hungary.png" %}">
                {% elif voca_book.from_lang == 'pl-PL' %} <img src="{% static "image/poland.png" %}">
                {% elif voca_book.from_lang == 'cs-CZ' %} <img src="{% static "image/czech.png" %}">
                {% elif voca_book.from_lang == 'sk-SK' %} <img src="{% static "image/slovakia.png" %}">
                {% elif voca_book.from_lang == 'pt-PT' %} <img src="{% static "image/portugal.png" %}">
                {% elif voca_book.from_lang == 'ro-RO' %} <img src="{% static "image/romania.png" %}">
                {% elif voca_book.from_lang == 'nl-NL' %} <img src="{% static "image/netherlands.png" %}">
                {% elif voca_book.from_lang == 'el-GR' %} <img src="{% static "image/greece.png" %}">
                {% elif voca_book.from_lang == 'da-DK' %} <img src="{% static "image/denmark.png" %}">
                {% elif voca_book.from_lang == 'no-NO' %} <img src="{% static "image/norway.png" %}">
                {% elif voca_book.from_lang == 'sv-SE' %} <img src="{% static "image/sweden.png" %}">
                {% elif voca_book.from_lang == 'fi-FI' %} <img src="{% static "image/finland.png" %}">
                {% endif %}
                <img class="arrow" src="{% static "image/right-arrow.png" %}">
                {% if voca_book.to_lang == 'ko-KR' %} <img src="{% static "image/korea.png" %}">
                {% elif voca_book.to_lang == 'ja-JP' %} <img src="{% static "image/japan.png" %}">
                {% elif voca_book.to_lang == 'zh-CN' %} <img src="{% static "image/china.png" %}">
                {% elif voca_book.to_lang == 'en-US' %} <img src="{% static "image/usa.png" %}">
                {% elif voca_book.to_lang == 'es-ES' %} <img src="{% static "image/spain.png" %}">
                {% elif voca_book.to_lang == 'it-IT' %} <img src="{% static "image/italy.png" %}">
                {% elif voca_book.to_lang == 'fr-FR' %} <img src="{% static "image/france.png" %}">
                {% elif voca_book.to_lang == 'de-DE' %} <img src="{% static "image/germany.png" %}">
                {% elif voca_book.to_lang == 'ru-RU' %} <img src="{% static "image/russia.png" %}">
                {% elif voca_book.to_lang == 'ar-SA' %} <img src="{% static "image/saudi-arabia.png" %}">
                {% elif voca_book.to_lang == 'he-IL' %} <img src="{% static "image/israel.png" %}">
                {% elif voca_book.to_lang == 'hi-IN' %} <img src="{% static "image/india.png" %}">
                {% elif voca_book.to_lang == 'id-ID' %} <img src="{% static "image/indonesia.png" %}">
                {% elif voca_book.to_lang == 'th-TH' %} <img src="{% static "image/thailand.png" %}">
                {% elif voca_book.to_lang == 'bn-BD' %} <img src="{% static "image/bangladesh.png" %}">
                {% elif voca_book.to_lang == 'tr-TR' %} <img src="{% static "image/turkey.png" %}">
                {% elif voca_book.to_lang == 'hu-HU' %} <img src="{% static "image/hungary.png" %}">
                {% elif voca_book.to_lang == 'pl-PL' %} <img src="{% static "image/poland.png" %}">
                {% elif voca_book.to_lang == 'cs-CZ' %} <img src="{% static "image/czech.png" %}">
                {% elif voca_book.to_lang == 'sk-SK' %} <img src="{% static "image/slovakia.png" %}">
                {% elif voca_book.to_lang == 'pt-PT' %} <img src="{% static "image/portugal.png" %}">
                {% elif voca_book.to_lang == 'ro-RO' %} <img src="{% static "image/romania.png" %}">
                {% elif voca_book.to_lang == 'nl-NL' %} <img src="{% static "image/netherlands.png" %}">
                {% elif voca_book.to_lang == 'el-GR' %} <img src="{% static "image/greece.png" %}">
                {% elif voca_book.to_lang == 'da-DK' %} <img src="{% static "image/denmark.png" %}">
                {% elif voca_book.to_lang == 'no-NO' %} <img src="{% static "image/norway.png" %}">
                {% elif voca_book.to_lang == 'sv-SE' %} <img src="{% static "image/sweden.png" %}">
                {% elif voca_book.to_lang == 'fi-FI' %} <img src="{% static "image/finland.png" %}">
                {% endif %}
            </div>
            <a href="{% url 'sword:detail' voca_book.id %}">{{ voca_book.title }}</a>
        </div>
        <div class="sub">
            <p>
                <span class="title">작성자</span>
                <span class="data">{{ voca_book.author.username }}</span>
            </p>
            <p>
                <span class="title">단어</span>
                <span class="data">{{ voca_book.word_set.count }}</span>
            </p>
            <p>
                <span class="title">조회수</span>
                <span class="data">{{ voca_book.view }}</span>
            </p>
            <p>
                <span class="title">즐겨찾기</span>
                <span class="data">{{ voca_book.voter.count }}</span>
            </p>
        </div>
        <div class="sub" style="margin-top: 0.3em;">
            <p>
                <span class="title">작성일</span>
                <span class="data">{{ voca_book.create_date }}</span>
            </p>
            <p>
                <span class="title">수정일</span>
                <span class="data">{{ voca_book.modify_date }}</span>
            </p>
        </div>
        {% if request.user == voca_book.author %}
        <div class="buttons">
            <a href="{% url 'sword:voca_book_modify' voca_book.id  %}">
                <img src="{% static "image/setting.png" %}">
                설정 편집
            </a>
            <a href="{% url 'sword:words_modify' voca_book.id  %}">
                <img src="{% static "image/edit.png" %}">
                단어 편집
            </a>
            <a href="javascript:void(0)" class="delete" data-uri="{% url 'sword:voca_book_delete' voca_book.id  %}">
                <img src="{% static "image/delete.png" %}">
                단어장 삭제
            </a>
        </div>
        {% endif %}
    </div>
    <div>
        <div class="word-list word-title">
            <span>단어 목록</span>
            {% if user.is_authenticated %}
            <select onchange="HideList(this.value);">
                <option value="all">전체 단어</option>
                <option value="mark">중요한 단어</option>
            </select>
            {% endif %}
        </div>
        <div class="word-all">
            {% if word_list %}
                {% for word in word_list %}
                <div class="word-list">
                    <div class="content">{{ word.content }}</div>
                    <div class="mean">{{ word.mean }}</div>
                    {% if user.is_authenticated %}
                        {% if word in user.word_voter.all %}
                        <a href="{% url 'sword:word_vote_cancel' word.id %}">
                            <img src="{% static "image/star.png" %}">
                        </a>
                        {% else %}
                        <a href="{% url 'sword:word_vote' word.id %}">
                            <img src="{% static "image/empty.png" %}">
                        </a>
                        {% endif %}
                    {% endif %}
                    <img src="{% static "image/speak.png" %}" onclick="speech('{{ word.content }}', '{{ voca_book.from_lang }}');"/>
                </div>
                {% endfor %}
            {% else %}
            <div class="word-list not-word-exist">
                단어가 존재하지 않습니다.
            </div>
            {% endif %}
        </div>
        <div class="word-mark" style="display: none;">
            {% if word_mark %}
                {% for word in word_mark %}
                <div class="word-list">
                    <div class="content">{{ word.content }}</div>
                    <div class="mean">{{ word.mean }}</div>
                    {% if user.is_authenticated %}
                        {% if word in user.word_voter.all %}
                        <a href="{% url 'sword:word_vote_cancel' word.id %}">
                            <img src="{% static "image/star.png" %}">
                        </a>
                        {% else %}
                        <a href="{% url 'sword:word_vote' word.id %}">
                            <img src="{% static "image/empty.png" %}">
                        </a>
                        {% endif %}
                    {% endif %}
                    <img src="{% static "image/speak.png" %}" onclick="speech('{{ word.content }}', '{{ voca_book.from_lang }}');"/>
                </div>
                {% endfor %}
            {% else %}
            <div class="word-list not-word-exist">
                중요 표시된 단어가 존재하지 않습니다.
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}