common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from word import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sword/', include('word.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

word/urls.py
from django.urls import path
from . import views

app_name = 'sword'

urlpatterns = [
    path('', views.index, name='index'),
    path('voca_book/<int:voca_id>', views.detail, name='detail'),
    path('voca_book/create/', views.voca_book_create, name='voca_book_create'),
    path('voca_book/modify/<int:voca_id>/', views.voca_book_modify, name='voca_book_modify'),
    path('voca_book/word/modify/<int:voca_id>/', views.words_modify, name='words_modify'),
    path('voca_book/delete/<int:voca_id>/', views.voca_book_delete, name='voca_book_delete'),
    path('voca_book/vote/<int:voca_id>/', views.voca_book_vote, name='voca_book_vote'),
    path('voca_book/vote/cancel/<int:voca_id>/', views.voca_vote_cancel, name='voca_vote_cancel'),
    path('voca_book/word/vote/<int:word_id>/', views.word_vote, name='word_vote'),
    path('voca_book/word/vote/cancel/<int:word_id>/', views.word_vote_cancel, name='word_vote_cancel'),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('sword:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="center-form">
    <div class="type">
        로그인
    </div>
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-input">
            <div class="set">
                <div class="title">
                    <label for="username">아이디</label>
                </div>
                <div class="value">
                    <input type="text" class="form-control" name="username" id="username"
                       placeholder="아이디를 입력해주세요." value="{{ form.username.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="set">
                <div class="title">
                    <label for="password">비밀번호</label>
                </div>
                <div class="value">
                    <input type="password" class="form-control" name="password" id="password"
                       placeholder="비밀번호를 입력해주세요." value="{{ form.password.value|default_if_none:'' }}">
                </div>
            </div>
        </div>
        <div class="submit">
            <button type="submit">로그인</button>
        </div>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="center-form">
    <div class="type">
        회원가입
    </div>
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-input">
            <div class="set">
                <div class="title">
                    <label for="username">
                        아이디
                        <strong>*</strong>
                    </label>
                </div>
                <div class="value">
                    <input type="text" class="form-control" name="username" id="username"
                        placeholder="아이디를 입력해주세요." value="{{ form.username.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="set">
                <div class="title">
                    <label for="password1">
                        비밀번호
                        <strong>*</strong>
                    </label>
                </div>
                <div class="value">
                    <input type="password" class="form-control" name="password1" id="password1"
                        placeholder="비밀번호를 입력해주세요." value="{{ form.password1.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="set">
                <div class="title">
                    <label for="password2">
                        비밀번호 확인
                        <strong>*</strong>
                    </label>
                </div>
                <div class="value">
                    <input type="password" class="form-control" name="password2" id="password2"
                        placeholder="비밀번호를 다시 입력해주세요." value="{{ form.password2.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="set">
                <div class="title">
                    <label for="email">이메일</label>
                </div>
                <div class="value">
                    <input type="text" class="form-control" name="email" id="email"
                        placeholder="이메일 주소를 입력해주세요." value="{{ form.email.value|default_if_none:'' }}">
                </div>
            </div>
        </div>
        <div class="submit">
            <button type="submit">생성하기</button>
        </div>
    </form>
</div>
{% endblock %}